---
- hosts: all
  serial: 1
  vars:
    - log: ../../offsets.csv
  tasks:
    - name: get time offset
      shell: ntpq -p | awk 'NR==3{print $9,$10}'
      register: result
    - name: log time offset
      lineinfile:
        line: "{{ inventory_hostname }}, {{ result.stdout }} miliseconds"
        insertafter: EOF
        dest: "{{ log }}"
      delegate_to: 127.0.0.1
